USE ecommerce_analytics;
SELECT * FROM customers LIMIT 5;
SELECT COUNT(*) FROM customers;
SHOW TABLES;
RENAME TABLE olist_customers_dataset TO customers;
DROP TABLE customers;
--- Rename Final Table
RENAME TABLE olist_customers_dataset TO customers;
RENAME TABLE olist_orders_dataset TO orders;
RENAME TABLE olist_products_dataset TO products;
RENAME TABLE olist_order_payments_dataset TO payments;
RENAME TABLE olist_order_reviews_dataset TO reviews;
RENAME TABLE olist_sellers_dataset TO sellers;
RENAME TABLE product_category_name_translation TO category_translation;
DROP TABLE olist_geolocation_dataset;
-- Rename order items table for clean naming
RENAME TABLE olist_order_items_dataset TO order_items;
SHOW TABLES;
--- Inspect Tables One by One to get understand about you table
--- Customers tables
-- Inspect customer data structure
SELECT * FROM customers LIMIT 5;
-- Verify customer data loaded correctly
SELECT * FROM customers LIMIT 5;
SELECT * FROM order_items;
-- Inspect order transaction data
SELECT * FROM orders LIMIT 5;
-- Inspect product information
SELECT * FROM products LIMIT 5;
-- Inspect payment transactions
SELECT * FROM payments LIMIT 5;
-- Inspect review data
SELECT * FROM reviews LIMIT 5;
-- Inspect seller information
SELECT * FROM sellers LIMIT 5;
-- Inspect category mapping
SELECT * FROM category_translation LIMIT 5;


-- -- BUSINESS QUESTION:
-- What is the total revenue generated by the e-commerce platform?

SELECT 
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM payments;
-- SUM(payment_value) adds all payment transactions
-- ROUND makes output cleaner
-- This gives total platform revenue


-- BUSINESS QUESTION:
-- How many total orders were placed?

SELECT 
    COUNT(DISTINCT order_id) AS total_orders
FROM orders;
-- DISTINCT avoids duplicate counting
-- COUNT gives total number of unique orders

-- BUSINESS QUESTION:
-- How many unique customers are present?

SELECT 
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers;
-- customer_unique_id represents actual unique customers
-- customer_id may repeat for multiple purchases


-- BUSINESS QUESTION:
-- What is the average order value?

SELECT 
    ROUND(AVG(payment_value), 2) AS average_order_value
FROM payments;
-- AVG calculates average transaction amount
-- Important business KPI


-- BUSINESS QUESTION:
-- Which payment methods generate the most revenue?

SELECT 
    payment_type,
    ROUND(SUM(payment_value), 2) AS revenue
FROM payments
GROUP BY payment_type
ORDER BY revenue DESC;
-- GROUP BY separates data by payment type
-- SUM calculates revenue contribution
-- ORDER BY ranks highest to lowest


-- Repeat Customers
-- BUSINESS QUESTION:
-- How many repeat customers exist?

SELECT 
    COUNT(*) AS repeat_customers
FROM (
    SELECT 
        c.customer_unique_id,
        COUNT(o.order_id) AS total_orders
    FROM customers c
    JOIN orders o 
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(o.order_id) > 1
) repeat_data;
-- Join customers with orders
-- Group by unique customer
-- Count number of orders
-- Filter customers with more than one order

-- Top 10 Customers by Revenue
-- BUSINESS QUESTION:
-- Identify top customers by revenue contribution

SELECT 
    c.customer_unique_id,
    ROUND(SUM(p.payment_value), 2) AS total_spent
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payments p 
    ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_spent DESC
LIMIT 10;


-- Average Orders Per Customer
-- BUSINESS QUESTION:
-- What is average purchase frequency per customer?
SELECT 
    ROUND(COUNT(o.order_id) / COUNT(DISTINCT c.customer_unique_id), 2) AS avg_orders_per_customer
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;
    
-- Top Customer States
-- BUSINESS QUESTION:
-- Which states have the highest customer concentration?

SELECT 
    customer_state,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC
LIMIT 10;


-- Revenue by Customer State
-- BUSINESS QUESTION:
-- Which customer states generate highest revenue?

SELECT 
    c.customer_state,
    ROUND(SUM(p.payment_value), 2) AS revenue
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payments p 
    ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC
LIMIT 10;


-- Top 10 Best-Selling Products
-- BUSINESS QUESTION:
-- Identify top 10 products by revenue

SELECT 
    oi.product_id,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM order_items oi
GROUP BY oi.product_id
ORDER BY total_revenue DESC
LIMIT 10;
-- Group products by product_id
-- Sum product prices
-- Rank highest revenue products


-- Check actual column names in category_translation
SELECT * FROM category_translation LIMIT 5;
-- Top Product Categories by Revenue
-- BUSINESS QUESTION:
-- Identify top revenue-generating product categories

SELECT 
    ct.product_category_name_english,
    ROUND(SUM(oi.price), 2) AS category_revenue
FROM order_items oi
JOIN products pr
    ON oi.product_id = pr.product_id
JOIN category_translation ct
    ON pr.product_category_name = ct.`ï»¿product_category_name`
GROUP BY ct.product_category_name_english
ORDER BY category_revenue DESC
LIMIT 10;

DESCRIBE category_translation;

-- Top revenue-generating product categories
SELECT 
    ct.product_category_name_english,
    ROUND(SUM(oi.price), 2) AS category_revenue
FROM order_items oi
JOIN products pr
    ON oi.product_id = pr.product_id
JOIN category_translation ct
    ON pr.product_category_name = ct.`ï»¿product_category_name`
GROUP BY ct.product_category_name_english
ORDER BY category_revenue DESC
LIMIT 10;


-- Lowest-performing categories
SELECT 
    ct.product_category_name_english,
    ROUND(SUM(oi.price), 2) AS category_revenue
FROM order_items oi
JOIN products pr
    ON oi.product_id = pr.product_id
JOIN category_translation ct
    ON pr.product_category_name = ct.`ï»¿product_category_name`
GROUP BY ct.product_category_name_english
ORDER BY category_revenue ASC
LIMIT 10;

-- Average product price by category
SELECT 
    ct.product_category_name_english,
    ROUND(AVG(oi.price), 2) AS avg_price
FROM order_items oi
JOIN products pr
    ON oi.product_id = pr.product_id
JOIN category_translation ct
    ON pr.product_category_name = ct.`ï»¿product_category_name`
GROUP BY ct.product_category_name_english
ORDER BY avg_price DESC
LIMIT 10;


-- Top sellers by revenue
SELECT 
    seller_id,
    ROUND(SUM(price), 2) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;
-- CSV import introduced encoding issue in category translation column name
-- Adjusted join condition using actual imported column name


-- Average Delivery Time
-- BUSINESS QUESTION:
-- What is the average delivery time in days?

SELECT 
    ROUND(
        AVG(DATEDIFF(order_delivered_customer_date, order_purchase_timestamp)),
        2
    ) AS avg_delivery_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;
-- DATEDIFF calculates delivery duration
-- AVG gives overall average delivery time
-- NULL deliveries excluded


-- Delayed Orders
-- BUSINESS QUESTION:
-- Count delayed deliveries

SELECT 
    COUNT(*) AS delayed_orders
FROM orders
WHERE order_delivered_customer_date > order_estimated_delivery_date;
-- Compare actual vs estimated delivery dates
-- Count orders delivered after expected date


-- Order Status Distribution
-- BUSINESS QUESTION:
-- Analyze order status distribution

SELECT 
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;


-- Average Review Score
-- BUSINESS QUESTION:
-- Find average customer review score

SELECT 
    ROUND(AVG(review_score), 2) AS avg_review_score
FROM reviews;


-- Review Score Distribution
-- BUSINESS QUESTION:
-- Review score breakdown

SELECT 
    review_score,
    COUNT(*) AS total_reviews
FROM reviews
GROUP BY review_score
ORDER BY review_score DESC;


-- Seller Performance by Delivery
-- BUSINESS QUESTION:
-- Top sellers by order count

SELECT 
    seller_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM order_items
GROUP BY seller_id
ORDER BY total_orders DESC
LIMIT 10;